# Generated by Django 5.2.1 on 2025-05-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20250509_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Whether the book is available for loan'),
        ),
    ]
