# Generated by Django 5.2.1 on 2025-05-27 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_book_is_available_borrowingrecord_delete_loan'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, help_text='Name of the publishing company', max_length=200),
        ),
    ]
